platform :ios, "13.0"
source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!

def common
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ActiveLabel'
  pod 'MJRefresh'
  pod 'LookinServer', :configurations => ['Debug']
end

target 'SwiftUI_UIKit' do
  use_modular_headers!
  common
end
